language: node_js
cache:
  yarn: true
  directories:
  - node_modules
node_js:
  - "node"
script:
  - npm run lint
  - npm run test
after_success: 'npm run coveralls'
deploy:
  - provider: npm
    email: "wxsms@foxmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true
      branch: master
